name: Java CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.TOKEN }}
          context: .
          push: true
          tags: ${{ secrets.LOGIN }}/docker_yandexrest:latest